#include "brvm.h"
#include "br_adapters.h"
#include <stdio.h>
#include <string.h>
static int F,T;
#define X(n,e) do{int q=(e);T++;printf("%s %s\n",q?"PASS":"FAIL",n);if(!q)F++;}while(0)
static int init(br_vm*v,br_memory_ctx*c){br_vm_config q={4096,64,64,BR_CAP_ALL,NULL,0};br_memory_adapter_init(c,BR_ADAPTER_DETERMINISTIC,7);return !br_vm_create(v,&br_hal_deterministic,c)&&!br_vm_initialize(v)&&!br_vm_configure(v,&q);}
static int exec1(unsigned op,int deny){br_vm v;br_memory_ctx c;br_insn z[4]={{0}};size_t n=2;int r,expect=BR_OK;if(!init(&v,&c))return 0;v.caps[0]=deny?0:BR_CAP_ALL;z[0]=(br_insn){op,BR_WRAP,0,0,0,0,0,0};z[1]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};if(op==BR_JMP||op==BR_JZ||op==BR_JNZ||op==BR_BEQ||op==BR_CALL)z[0].imm=1;if(op==BR_DIVU||op==BR_MODU){z[0].rb=1;br_vm_reg(&v,1)[0]=1;}if(op==BR_SHL||op==BR_SHR||op==BR_ASHR||op==BR_ROL||op==BR_ROR)z[0].imm=1;if(op==BR_BITTST)z[0].imm=0;if(op==BR_SVC)z[0].imm=BR_SVC_NOP;if(op==BR_TRAP){z[0].imm=BR_TRAP_EXPLICIT;expect=BR_ESTATE;}if(op==BR_JMPR)br_vm_reg(&v,0)[0]=1;if(op==BR_POP){z[0]=(br_insn){BR_PUSH,BR_WRAP,0,0,0,0,0,0};z[1]=(br_insn){BR_POP,BR_WRAP,1,0,0,0,0,0};z[2]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};n=3;}if(op==BR_RET){z[0]=(br_insn){BR_CALL,BR_WRAP,0,0,0,0,0,2};z[1]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};z[2]=(br_insn){BR_RET,BR_WRAP,0,0,0,0,0,0};n=3;}if(op==BR_LEAVE){z[0]=(br_insn){BR_ENTER,BR_WRAP,0,0,0,0,0,0};z[1]=(br_insn){BR_LEAVE,BR_WRAP,0,0,0,0,0,0};z[2]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};n=3;}if(deny){z[0]=(br_insn){op,BR_WRAP,0,0,0,0,0,0};if(op==BR_JMP||op==BR_JZ||op==BR_JNZ||op==BR_BEQ||op==BR_CALL)z[0].imm=1;if(op==BR_SVC)z[0].imm=BR_SVC_NOP;if(op==BR_TRAP)z[0].imm=BR_TRAP_EXPLICIT;n=2;expect=BR_ECAP;}r=br_vm_load_code(&v,z,n);if(!r)r=br_vm_run(&v,32);r=(r==expect)&&(deny?v.trap==BR_TRAP_CAPABILITY:op==BR_TRAP?v.trap==BR_TRAP_EXPLICIT:1);br_vm_destroy(&v);return r;}
static int opcode_all(int deny){unsigned i;for(i=0;i<BR_OPCODES;i++)if(!exec1(i,deny)){printf("opcode_%u_%s failed\n",i,deny?"negative":"positive");return 0;}return 1;}
static int arithmetic(void){br_vm v;br_memory_ctx c;br_insn z[]={{BR_ADD,BR_CHECKED,2,0,1,0,0,0},{BR_SUB,BR_WRAP,3,2,1,0,0,0},{BR_MUL,BR_WRAP,4,0,1,0,0,0},{BR_DIVU,BR_WRAP,5,4,1,0,0,0},{BR_MODU,BR_WRAP,6,4,1,0,0,0},{BR_NEG,BR_WRAP,7,1,0,0,0,0},{BR_CMP,BR_WRAP,0,0,1,0,0,0},{BR_HALT,0,0,0,0,0,0,0}};int q;if(!init(&v,&c))return 0;v.caps[0]=BR_CAP_ALL;br_vm_reg(&v,0)[0]=9;br_vm_reg(&v,1)[0]=3;q=!br_vm_load_code(&v,z,8)&&!br_vm_run(&v,64)&&br_vm_reg(&v,2)[0]==12&&br_vm_reg(&v,3)[0]==9&&br_vm_reg(&v,4)[0]==27&&br_vm_reg(&v,5)[0]==9&&br_vm_reg(&v,6)[0]==0;br_vm_destroy(&v);return q;}
static int logic_shift(void){br_vm v;br_memory_ctx c;br_insn z[]={{BR_AND,0,2,0,1,0,0,0},{BR_OR,0,3,0,1,0,0,0},{BR_XOR,0,4,0,1,0,0,0},{BR_NOT,0,5,0,0,0,0,0},{BR_SHL,0,6,0,0,0,0,1},{BR_SHR,0,7,6,0,0,0,1},{BR_BITTST,0,0,0,0,0,0,3},{BR_ROL,0,8,0,0,0,0,1},{BR_ROR,0,9,8,0,0,0,1},{BR_ASHR,0,10,11,0,0,BR_IF_SIGNED,1},{BR_HALT,0,0,0,0,0,0,0}};int q;if(!init(&v,&c))return 0;v.caps[0]=BR_CAP_ALL;br_vm_reg(&v,0)[0]=10;br_vm_reg(&v,1)[0]=12;br_vm_reg(&v,11)[BR_LIMBS-1]=1ULL<<63;q=!br_vm_load_code(&v,z,11)&&!br_vm_run(&v,64)&&br_vm_reg(&v,2)[0]==8&&br_vm_reg(&v,3)[0]==14&&br_vm_reg(&v,4)[0]==6&&br_vm_reg(&v,7)[0]==10&&br_vm_reg(&v,9)[0]==10&&(br_vm_reg(&v,10)[BR_LIMBS-1]>>63);br_vm_destroy(&v);return q;}
static int memory_call_abi(void){br_vm v;br_memory_ctx c;br_insn z[]={{BR_MOVI,0,0,0,0,0,0,8},{BR_MOVI,0,1,0,0,0,0,77},{BR_STOREX,0,0,0,1,0,0,0},{BR_LOADX,0,2,0,0,0,0,0},{BR_CALL,0,0,0,0,0,0,7},{BR_HALT,0,0,0,0,0,0,0},{BR_NOP,0,0,0,0,0,0,0},{BR_ENTER,0,0,0,0,0,0,0},{BR_MOVI,0,3,0,0,0,0,99},{BR_LEAVE,0,0,0,0,0,0,0},{BR_RET,0,0,0,0,0,0,0}};int q;if(!init(&v,&c))return 0;v.caps[0]=BR_CAP_ALL;br_vm_reg(&v,8)[0]=0x55;q=!br_vm_load_code(&v,z,11)&&!br_vm_run(&v,64)&&br_vm_reg(&v,2)[0]==77&&br_vm_reg(&v,3)[0]==99&&br_vm_reg(&v,8)[0]==0x55&&v.sp==0&&BR_ABI_FP==14&&BR_ABI_PRESERVED_FIRST==8&&BR_ABI_PRESERVED_LAST==13;br_vm_destroy(&v);return q;}
static int modes_traps(void){br_vm v;br_memory_ctx c;br_insn z[]={{BR_ADD,BR_CHECKED,0,0,1,0,0,0},{BR_HALT,0,0,0,0,0,0,0}};int q;if(!init(&v,&c))return 0;v.caps[0]=BR_CAP_ALL;memset(br_vm_reg(&v,0),0xff,BR_LIMBS*8u);br_vm_reg(&v,1)[0]=1;q=!br_vm_load_code(&v,z,2)&&br_vm_run(&v,8)==BR_ESTATE&&v.trap==BR_TRAP_OVERFLOW;br_vm_reset(&v,1);v.caps[0]=BR_CAP_ALL;z[0]=(br_insn){BR_DIVU,0,0,0,1,0,0,0};q=q&&!br_vm_load_code(&v,z,2)&&br_vm_run(&v,8)==BR_ESTATE&&v.trap==BR_TRAP_DIV_ZERO;br_vm_destroy(&v);return q;}
static int trap_table(void){unsigned a[]={BR_TRAP_BAD_OPCODE,BR_TRAP_MALFORMED,BR_TRAP_REGISTER,BR_TRAP_BOUNDS,BR_TRAP_ACCESS,BR_TRAP_CAPABILITY,BR_TRAP_DIV_ZERO,BR_TRAP_OVERFLOW,BR_TRAP_STACK_OVERFLOW,BR_TRAP_STACK_UNDERFLOW,BR_TRAP_RESOURCE,BR_TRAP_BUDGET,BR_TRAP_DEVICE,BR_TRAP_SIGNATURE};size_t i;for(i=0;i<sizeof(a)/sizeof(*a);i++){br_vm v;br_memory_ctx c;br_insn z={0};z=(br_insn){BR_TRAP,0,0,0,0,0,0,a[i]};if(!init(&v,&c))return 0;v.caps[0]=BR_CAP_ALL;if(br_vm_load_code(&v,&z,1)||br_vm_run(&v,2)!=BR_ESTATE||v.trap!=a[i]){br_vm_destroy(&v);return 0;}br_vm_destroy(&v);}return 1;}
static int ia_(void){br_insn z[]={{BR_HALT,0,0,0,0,0,0,0}};uint8_t b[256];size_t n;br_vm v;br_memory_ctx c;br_trap_frame f;int q=br_image_encode(b,sizeof(b),&n,z,1,1,BR_CAP_CONTROL,NULL,0,BR_IMAGE_FLAG_FACTORY)==0&&b[8]==BR_ABI_VERSION&&b[9]==BR_ISA_MARKER&&b[12]==BR_OPCODES&&!memcmp(b+64,"BR4.3-LCTL",11);if(!q||!init(&v,&c))return 0;v.iv_=0;q=!br_image_load(&v,b,n,NULL,0,0)&&v.ia_==2&&v.ii_==1&&!br_vm_trap_frame(&v,&f)&&f.abi==2&&f.isa_minor==1;br_vm_destroy(&v);return q;}
int main(void){X("opcode_positive_41",opcode_all(0));X("opcode_capability_negative_41",opcode_all(1));X("arithmetic_contract",arithmetic());X("logical_shift_rotate_contract",logic_shift());X("memory_call_abi_contract",memory_call_abi());X("arithmetic_modes_and_traps",modes_traps());X("canonical_trap_table_14",trap_table());X("image_abi2_isa11_trap_frame",ia_());printf("{\"suite\":\"BR-430\",\"tests\":%d,\"failures\":%d,\"opcode_positive\":41,\"opcode_negative\":41,\"canonical_traps\":14,\"result\":\"%s\"}\n",T,F,F?"FAIL":"PASS");return F?1:0;}
