#include "brvm.h"
#include "br_adapters.h"
#include <stdio.h>
#include <string.h>
static int f,n;
#define T(s,e) do{int q=(e);n++;printf("%s %s\n",q?"PASS":"FAIL",s);if(!q)f++;}while(0)
static int init(br_vm*v,br_memory_ctx*c,const br_device*d,size_t dn,uint32_t sb){br_vm_config q={256,sb,256,BR_CAP_ALL,d,dn};br_memory_adapter_init(c,BR_ADAPTER_DETERMINISTIC,7);return !br_vm_create(v,&br_hal_deterministic,c)&&!br_vm_initialize(v)&&!br_vm_configure(v,&q);}
static void r(br_vm*v,unsigned x,uint64_t y){br_vm_reg(v,x)[0]=y;}
static int one(br_vm*v,unsigned svc,uint16_t fl,uint32_t cap,uint64_t a,uint64_t b){br_insn c[]={{BR_SVC,BR_WRAP,2,0,1,1,fl,svc},{BR_HALT,BR_WRAP,0,0,0,0,0,0}};int z;v->caps[1]=cap;r(v,0,a);r(v,1,b);z=br_vm_load_code(v,c,2);return z?z:br_vm_run(v,8);}
static int discovery(void){br_vm v;br_memory_ctx c;br_device d[]={{BR_DEVICE_NETWORK,BR_CAP_SERVICE},{BR_DEVICE_WALL_CLOCK,BR_CAP_SERVICE}};int ok=init(&v,&c,d,2,32);if(ok){ok=!one(&v,BR_SVC_DEVICE_ENUM,0,BR_CAP_SERVICE,0,0)&&br_vm_reg(&v,2)[0]==9&&br_vm_reg(&v,2)[1]==BR_DEVICE_CONSOLE&&br_vm_reg(&v,2)[2]==BR_CAP_SERVICE&&br_vm_reg(&v,2)[3]==BR_DEVICE_ABI_VERSION&&br_vm_reg(&v,2)[4]==BR_DEVICE_BUFFER_BYTES&&br_vm_reg(&v,2)[5]==BR_DEVICE_NONDETERMINISTIC&&br_vm_reg(&v,2)[6]==BR_DEVICE_BUFFER_BYTES;br_vm_reset(&v,1);ok=ok&&!one(&v,BR_SVC_DEVICE_ENUM,0,BR_CAP_SERVICE,1,0)&&br_vm_reg(&v,2)[1]==BR_DEVICE_BLOCK&&br_vm_reg(&v,2)[6]==(BR_STORAGE_OBJECT_BYTES-48u)*BR_STORAGE_GUEST_OBJECTS;br_vm_reset(&v,1);ok=ok&&!one(&v,BR_SVC_DEVICE_ENUM,0,BR_CAP_SERVICE,7,0)&&br_vm_reg(&v,2)[1]==BR_DEVICE_NETWORK&&(br_vm_reg(&v,2)[5]&BR_DEVICE_OPTIONAL);br_vm_reset(&v,1);ok=ok&&!one(&v,BR_SVC_DEVICE_ENUM,0,BR_CAP_SERVICE,8,0)&&br_vm_reg(&v,2)[1]==BR_DEVICE_WALL_CLOCK&&(br_vm_reg(&v,2)[5]&(BR_DEVICE_OPTIONAL|BR_DEVICE_NONDETERMINISTIC))==(BR_DEVICE_OPTIONAL|BR_DEVICE_NONDETERMINISTIC);}br_vm_destroy(&v);{br_vm x;br_memory_ctx m;br_device bad[]={{9,BR_CAP_SERVICE},{8,BR_CAP_SERVICE}};br_vm_config q={32,8,8,BR_CAP_ALL,bad,2};br_memory_adapter_init(&m,BR_ADAPTER_MEMORY,1);ok=ok&&!br_vm_create(&x,&br_hal_memory,&m)&&!br_vm_initialize(&x)&&br_vm_configure(&x,&q)==BR_EINVAL;br_vm_destroy(&x);}return ok;}
static int generic(void){br_vm v;br_memory_ctx c;br_device d={BR_DEVICE_NETWORK,BR_CAP_SERVICE};int ok=init(&v,&c,&d,1,64);memcpy(v.memory,"ABCDEFGH",8);ok=ok&&!one(&v,BR_SVC_DEVICE_CALL,(uint16_t)((8u<<8)|3u),BR_CAP_SERVICE,0,0)&&c.dc_s==1&&v.memory[0]==BR_DEVICE_NETWORK&&v.memory[4]==3;br_vm_reset(&v,1);v.memory[0]=1;ok=ok&&one(&v,BR_SVC_DEVICE_CALL,(uint16_t)((8u<<8)|1u),0,0,0)==BR_ECAP&&v.trap==BR_TRAP_CAPABILITY;br_vm_reset(&v,1);ok=ok&&one(&v,BR_SVC_DEVICE_CALL,(uint16_t)((65u<<8)|1u),BR_CAP_SERVICE,0,0)==BR_EBOUNDS&&v.trap==BR_TRAP_BOUNDS;br_vm_destroy(&v);return ok;}
static int console_clock_entropy(void){br_vm a,b;br_memory_ctx ca,cb;uint8_t x[8],y[8];uint64_t t1,t2;int ok=init(&a,&ca,0,0,64)&&init(&b,&cb,0,0,64);br_memory_adapter_console(&ca,(const uint8_t*)"xy",2);if(ok){ok=!one(&a,BR_SVC_CONSOLE_READ,0,BR_CAP_SERVICE,0,2)&&!memcmp(a.memory,"xy",2);br_vm_reset(&a,1);memcpy(a.memory,"z",1);ok=ok&&!one(&a,BR_SVC_CONSOLE_WRITE,0,BR_CAP_SERVICE,0,1)&&ca.console_out_n==1&&ca.console_out[0]=='z';br_vm_reset(&a,1);ok=ok&&!one(&a,BR_SVC_CONSOLE_WRITE,0,BR_CAP_SERVICE,0,0);br_vm_reset(&a,1);ok=ok&&!one(&a,BR_SVC_TIMER,0,BR_CAP_SERVICE,0,0);t1=br_vm_reg(&a,2)[0];br_vm_reset(&a,1);ok=ok&&!one(&a,BR_SVC_TIMER,0,BR_CAP_SERVICE,0,0);t2=br_vm_reg(&a,2)[0];br_vm_reset(&a,1);ok=ok&&!one(&a,BR_SVC_ENTROPY,0,BR_CAP_SERVICE,0,8);memcpy(x,a.memory,8);br_vm_reset(&b,1);ok=ok&&!one(&b,BR_SVC_ENTROPY,0,BR_CAP_SERVICE,0,8);memcpy(y,b.memory,8);ok=ok&&t2>t1&&!memcmp(x,y,8);}br_vm_destroy(&a);br_vm_destroy(&b);return ok;}
static int block_mono(void){br_vm v;br_memory_ctx c;int ok=init(&v,&c,0,0,64);memcpy(v.memory,"data",4);if(ok){ok=!one(&v,BR_SVC_STORAGE_WRITE,0,BR_CAP_STATE,0,4);br_vm_reset(&v,1);memset(v.memory,0,4);ok=ok&&!one(&v,BR_SVC_STORAGE_READ,0,BR_CAP_STATE,0,4)&&!memcmp(v.memory,"data",4);br_vm_reset(&v,1);ok=ok&&!one(&v,BR_SVC_MONOTONIC,0,BR_CAP_STATE,0,0)&&br_vm_reg(&v,2)[0]==0;ok=ok&&!br_vm_save(&v)&&c.monotonic>0;}br_vm_destroy(&v);return ok;}
static int mailbox(void){br_vm v;br_memory_ctx c;uint8_t o[64];size_t z=0;int ok=init(&v,&c,0,0,64);if(ok){ok=!br_vm_mailbox_host_put(&v,(const uint8_t*)"hi",2)&&br_vm_mailbox_host_put(&v,(const uint8_t*)"x",1)==BR_ERESOURCE;v.caps[1]=BR_CAP_SERVICE;r(&v,0,0);r(&v,1,2);{br_insn q[]={{BR_SVC,BR_WRAP,2,0,1,1,0,BR_SVC_MAILBOX_GET},{BR_HALT,BR_WRAP,0,0,0,0,0,0}};ok=ok&&!br_vm_load_code(&v,q,2)&&!br_vm_run(&v,8)&&!memcmp(v.memory,"hi",2);}br_vm_reset(&v,1);memcpy(v.memory,"go",2);ok=ok&&!one(&v,BR_SVC_MAILBOX_PUT,0,BR_CAP_SERVICE,0,2)&&!br_vm_mailbox_host_get(&v,o,sizeof(o),&z)&&z==2&&!memcmp(o,"go",2);}br_vm_destroy(&v);return ok;}
static int quotas(void){br_vm v;br_memory_ctx c;br_insn q[20];int i,ok=init(&v,&c,0,0,64);if(!ok)return 0;v.caps[1]=BR_CAP_SERVICE;r(&v,0,0);r(&v,1,1);for(i=0;i<9;i++)q[i]=(br_insn){BR_SVC,BR_WRAP,2,0,1,1,0,BR_SVC_ENTROPY};q[9]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};ok=!br_vm_load_code(&v,q,10)&&br_vm_run(&v,20)==BR_ERESOURCE&&v.trap==BR_TRAP_RESOURCE;br_vm_reset(&v,1);v.caps[1]=BR_CAP_STATE;r(&v,0,0);r(&v,1,1);for(i=0;i<5;i++)q[i]=(br_insn){BR_SVC,BR_WRAP,2,0,1,1,0,BR_SVC_STORAGE_WRITE};q[5]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};ok=ok&&!br_vm_load_code(&v,q,6)&&br_vm_run(&v,20)==BR_ERESOURCE&&v.trap==BR_TRAP_RESOURCE;br_vm_reset(&v,1);v.sb_=2;v.caps[1]=BR_CAP_SERVICE;for(i=0;i<3;i++)q[i]=(br_insn){BR_SVC,BR_WRAP,2,0,1,1,0,BR_SVC_NOP};q[3]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};ok=ok&&!br_vm_load_code(&v,q,4)&&br_vm_run(&v,20)==BR_ERESOURCE&&v.trap==BR_TRAP_RESOURCE;br_vm_destroy(&v);return ok;}
static int apdu_dev(void){br_vm v;br_memory_ctx c;uint8_t q[28]={0x81,BR_APDU_LOAD,0,0,1},o[64];size_t z;int ok=init(&v,&c,0,0,64);q[10]=16;q[12]=BR_HALT;q[13]=BR_WRAP;z=br_apdu(&v,q,sizeof(q),o,sizeof(o));ok=ok&&z==8&&o[0]==0x90&&o[1]==0;br_vm_destroy(&v);return ok;}
static int rngfail(void*x,uint8_t*o,size_t n){(void)x;(void)o;(void)n;return BR_EIO;}
static int entropy_failure(void){br_vm v;br_memory_ctx c;br_hal h=br_hal_memory;int ok;h.rb_=rngfail;br_memory_adapter_init(&c,BR_ADAPTER_MEMORY,1);ok=init(&v,&c,0,0,16);br_vm_destroy(&v);if(!ok)return 0;ok=!br_vm_create(&v,&h,&c)&&!br_vm_initialize(&v);{br_vm_config q={64,16,16,BR_CAP_ALL,0,0};ok=ok&&!br_vm_configure(&v,&q);}if(ok)ok=one(&v,BR_SVC_ENTROPY,0,BR_CAP_SERVICE,0,8)==BR_EIO&&v.trap==BR_TRAP_HOST;br_vm_destroy(&v);return ok;}
static int wall_clock_optional(void){br_vm v;br_memory_ctx c;br_device d={BR_DEVICE_WALL_CLOCK,BR_CAP_SERVICE};int ok=init(&v,&c,&d,1,32);if(ok){memset(v.memory,0,8);ok=!one(&v,BR_SVC_DEVICE_CALL,(uint16_t)((8u<<8)|1u),BR_CAP_SERVICE,0,0)&&br_vm_reg(&v,2)[0]==8&&*(uint64_t*)v.memory>0;}br_vm_destroy(&v);return ok;}
static int no_network_default(void){br_vm v;br_memory_ctx c;int ok=init(&v,&c,0,0,16);if(ok){ok=!one(&v,BR_SVC_DEVICE_ENUM,0,BR_CAP_SERVICE,7,0)&&br_vm_reg(&v,2)[0]==7&&br_vm_reg(&v,2)[1]==0;}br_vm_destroy(&v);return ok;}
int main(void){T("device_abi_version_ids_caps_flags_order",discovery());T("generic_device_op_buffers_caps_bounds",generic());T("console_clock_entropy_deterministic",console_clock_entropy());T("persistent_block_and_monotonic",block_mono());T("bidirectional_owned_mailbox",mailbox());T("calls_bytes_storage_entropy_quotas",quotas());T("development_apdu_class",apdu_dev());T("entropy_failure_fail_closed",entropy_failure());T("optional_wall_clock_extension",wall_clock_optional());T("network_absent_by_default",no_network_default());printf("{\"suite\":\"BR-470\",\"tests\":%d,\"failures\":%d,\"result\":\"%s\"}\n",n,f,f?"FAIL":"PASS");return f?1:0;}
