#include "brvm.h"
#include "br_adapters.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
static int failures,tests;
#define T(n,e) do{int ok=(e);tests++;printf("%s %s\n",ok?"PASS":"FAIL",n);if(!ok)failures++;}while(0)
static const br_insn boot[]={{BR_MOVI,BR_WRAP,0,0,0,0,0,40},{BR_MOVI,BR_WRAP,1,0,0,0,0,2},{BR_ADD,BR_CHECKED,2,0,1,0,0,0},{BR_MOVI,BR_WRAP,3,0,0,0,0,42},{BR_CMP,BR_WRAP,0,2,3,0,0,0},{BR_HALT,BR_WRAP,0,0,0,0,0,0}};
static int init(br_vm*v,const br_hal*h,void*c,uint32_t hb,const br_device*d,size_t dn){br_vm_config q={4096,64,hb,BR_CAP_ALL,d,dn};return br_vm_create(v,h,c)==0&&br_vm_initialize(v)==0&&br_vm_configure(v,&q)==0;}
static int makeimg(uint8_t*out,size_t cap,size_t*n){return br_image_encode(out,cap,n,boot,sizeof(boot)/sizeof(*boot),6,BR_CAP_ALL,NULL,0,BR_IMAGE_FLAG_FACTORY)==0;}
static int runimg(const br_hal*h,void*c,uint8_t*im,size_t n,uint64_t*r2,uint32_t*status,uint32_t*trap){br_vm v;int ok=init(&v,h,c,64,NULL,0);if(ok){v.iv_=0;ok=br_image_load(&v,im,n,NULL,0,0)==0&&br_vm_run(&v,64)==0;*r2=br_vm_reg(&v,2)[0];*status=v.status;*trap=v.trap;}br_vm_destroy(&v);return ok;}
static int lc_(void){br_vm v;br_memory_ctx c;int ok;br_memory_adapter_init(&c,BR_ADAPTER_MEMORY,1);ok=br_vm_create(&v,&br_hal_memory,&c)==0&&v.lc_==BR_LIFE_CREATED&&br_vm_initialize(&v)==0&&v.lc_==BR_LIFE_INITIALIZED;{br_vm_config q={128,8,8,BR_CAP_ALL,NULL,0};ok=ok&&br_vm_configure(&v,&q)==0&&v.lc_==BR_LIFE_CONFIGURED;}ok=ok&&br_vm_load_code(&v,boot,6)==0&&v.lc_==BR_LIFE_LOADED&&br_vm_verify(&v)==0&&v.lc_==BR_LIFE_VERIFIED&&br_vm_start(&v)==0&&br_vm_suspend(&v)==0&&v.lc_==BR_LIFE_SUSPENDED&&br_vm_resume(&v)==0&&br_vm_run(&v,64)==0&&v.status==BR_HALTED;br_vm_reset(&v,1);ok=ok&&v.lc_==BR_LIFE_CONFIGURED&&br_vm_fault(&v,BR_TRAP_STATE)<0&&v.lc_==BR_LIFE_FAULTED;br_vm_destroy(&v);return ok&&v.lc_==BR_LIFE_DESTROYED;}
static int isolation(void){br_vm a,b;br_memory_ctx ca,cb;int ok;br_memory_adapter_init(&ca,BR_ADAPTER_MEMORY,11);br_memory_adapter_init(&cb,BR_ADAPTER_MEMORY,22);if(!init(&a,&br_hal_memory,&ca,64,NULL,0)||!init(&b,&br_hal_memory,&cb,64,NULL,0))return 0;br_vm_reg(&a,0)[0]=123;a.memory[0]=0xaa;a.caps[1]=BR_CAP_SERVICE;a.su_=7;ok=br_vm_reg(&b,0)[0]==0&&b.memory[0]==0&&b.caps[1]==0&&b.su_==0&&a.hc_!=b.hc_;br_vm_destroy(&a);br_vm_destroy(&b);return ok;}
static int memory_hal_contract(const br_hal*h,enum br_memory_adapter_kind kind){br_memory_ctx c;uint8_t a[16]={1,2,3},b[32]={0};size_t n=0;uint64_t m=0,t=0;br_memory_adapter_init(&c,kind,123);br_memory_adapter_console(&c,(const uint8_t*)"xy",2);if(!h->sr_||!h->sw_||!h->sc_||!h->se_||!h->mr_||!h->mc_||!h->vs_||!h->rb_||!h->cr_||!h->ci_||!h->co_||!h->dc_||!h->panic||!h->yield||!h->lock||!h->unlock)return 0;if(h->sw_(&c,0,a,3)||h->sc_(&c,0)||h->sr_(&c,0,b,sizeof(b),&n)||n!=3||memcmp(a,b,3))return 0;if(h->se_(&c,0)||h->mr_(&c,&m)||m||h->mc_(&c,4)||h->mr_(&c,&m)||m!=4)return 0;if(h->rb_(&c,b,8)||h->cr_(&c,&t)||!t||h->ci_(&c,b,2,&n)||n!=2||memcmp(b,"xy",2)||h->co_(&c,(const uint8_t*)"z",1))return 0;if(h->dc_(&c,7,a,3,b,sizeof(b),&n)||n!=7||c.dc_s!=1)return 0;h->panic(&c,9);if(c.panic_code!=9||h->yield(&c)||h->lock(&c)||h->lock(&c)==0||h->unlock(&c))return 0;return 1;}
static void cleanup(const char*p){char q[256];unsigned i;for(i=0;i<2;i++){snprintf(q,sizeof(q),"%s.ctl.%u",p,i);remove(q);snprintf(q,sizeof(q),"%s.ctl.%u.tmp",p,i);remove(q);snprintf(q,sizeof(q),"%s.img.%u",p,i);remove(q);snprintf(q,sizeof(q),"%s.img.%u.tmp",p,i);remove(q);}snprintf(q,sizeof(q),"%s.mono",p);remove(q);snprintf(q,sizeof(q),"%s.mono.tmp",p);remove(q);}
static int file_adapter_contract(int windows){uint8_t a[4]={9,8,7,6},b[8];size_t n=0;uint64_t m=0;char p[128];int r;snprintf(p,sizeof(p),"/tmp/br410-%s-%ld",windows?"win":"posix",(long)getpid());cleanup(p);if(windows){br_windows_ctx c;if(br_windows_adapter_init(&c,p))return 0;r=br_hal_windows.sw_(&c,0,a,4)||br_hal_windows.sc_(&c,0)||br_hal_windows.sr_(&c,0,b,sizeof(b),&n)||n!=4||memcmp(a,b,4)||br_hal_windows.mc_(&c,3)||br_hal_windows.mr_(&c,&m)||m!=3;}else{br_posix_ctx c;if(br_posix_adapter_init(&c,p))return 0;r=br_hal_posix.sw_(&c,0,a,4)||br_hal_posix.sc_(&c,0)||br_hal_posix.sr_(&c,0,b,sizeof(b),&n)||n!=4||memcmp(a,b,4)||br_hal_posix.mc_(&c,3)||br_hal_posix.mr_(&c,&m)||m!=3;}cleanup(p);return !r;}
static int parity(void){uint8_t im[512];size_t n;uint64_t a,b,c;uint32_t as,at,bs,bt,cs,ct;br_memory_ctx ma,mb,mc;if(!makeimg(im,sizeof(im),&n))return 0;br_memory_adapter_init(&ma,BR_ADAPTER_MEMORY,1);br_memory_adapter_init(&mb,BR_ADAPTER_DETERMINISTIC,1);br_memory_adapter_init(&mc,BR_ADAPTER_BARE_METAL,1);return runimg(&br_hal_memory,&ma,im,n,&a,&as,&at)&&runimg(&br_hal_deterministic,&mb,im,n,&b,&bs,&bt)&&runimg(&br_hal_baremetal,&mc,im,n,&c,&cs,&ct)&&a==42&&a==b&&b==c&&as==bs&&bs==cs&&at==bt&&bt==ct;}
static int persistence(void){br_memory_ctx c;br_vm a,b;int ok;br_memory_adapter_init(&c,BR_ADAPTER_MEMORY,1);if(!init(&a,&br_hal_memory,&c,64,NULL,0))return 0;a.cw_=0x12345678;if(br_vm_save(&a)||br_vm_save(&a)){br_vm_destroy(&a);return 0;}if(!init(&b,&br_hal_memory,&c,64,NULL,0)){br_vm_destroy(&a);return 0;}ok=br_vm_recover(&b)==0&&b.cw_==0x12345678&&b.pg_==2&&c.monotonic==2;c.monotonic=99;br_vm_reset(&b,1);ok=ok&&br_vm_recover(&b)==BR_EREPLAY&&b.trap==BR_TRAP_REPLAY;br_vm_destroy(&a);br_vm_destroy(&b);return ok;}
static int error_images(void){uint8_t im[512],x[512];size_t n;br_vm v;br_memory_ctx c;int ok=1;if(!makeimg(im,sizeof(im),&n))return 0;br_memory_adapter_init(&c,BR_ADAPTER_MEMORY,1);if(!init(&v,&br_hal_memory,&c,64,NULL,0))return 0;v.iv_=0;memcpy(x,im,n);x[8]=3;ok=ok&&br_image_load(&v,x,n,NULL,0,0)==BR_EABI&&v.trap==BR_TRAP_UNSUPPORTED_ABI;br_vm_reset(&v,1);v.iv_=0;memcpy(x,im,n);x[12]=BR_OPCODES+1;ok=ok&&br_image_load(&v,x,n,NULL,0,0)==BR_EISA&&v.trap==BR_TRAP_UNSUPPORTED_ISA;br_vm_reset(&v,1);v.iv_=0;memcpy(x,im,n);x[BR_IMAGE_HEADER]^=1;ok=ok&&br_image_load(&v,x,n,NULL,0,0)==BR_EINTEGRITY&&v.trap==BR_TRAP_INTEGRITY;br_vm_reset(&v,1);v.iv_=0;ok=ok&&br_image_load(&v,im,n-1,NULL,0,0)==BR_EIMAGE&&v.trap==BR_TRAP_BAD_IMAGE;br_vm_reset(&v,1);v.iv_=7;ok=ok&&br_image_load(&v,im,n,NULL,0,0)==BR_EREPLAY;br_vm_destroy(&v);return ok;}
static int sandbox(void){br_memory_ctx c;br_vm v;br_insn code[4];br_device dev={7,BR_CAP_SERVICE};int ok;br_memory_adapter_init(&c,BR_ADAPTER_DETERMINISTIC,123);if(!init(&v,&br_hal_deterministic,&c,2,&dev,1))return 0;memset(code,0,sizeof(code));code[0]=(br_insn){BR_MOVI,BR_WRAP,0,0,0,0,0,0};code[1]=(br_insn){BR_MOVI,BR_WRAP,1,0,0,0,0,8};code[2]=(br_insn){BR_SVC,BR_WRAP,2,0,1,1,0,10};code[3]=(br_insn){BR_HALT,BR_WRAP,0,0,0,0,0,0};v.caps[1]=BR_CAP_SERVICE;ok=br_vm_load_code(&v,code,4)==0&&br_vm_run(&v,16)==0&&c.rng!=123;br_vm_reset(&v,1);v.caps[1]=0;ok=ok&&br_vm_load_code(&v,code,4)==0&&br_vm_run(&v,16)==BR_ECAP&&v.trap==BR_TRAP_CAPABILITY;br_vm_reset(&v,1);v.caps[1]=BR_CAP_SERVICE;code[0].imm=BR_MEMORY_BYTES-4;code[1].imm=8;ok=ok&&br_vm_load_code(&v,code,4)==0&&br_vm_run(&v,16)==BR_EBOUNDS&&v.trap==BR_TRAP_BOUNDS;br_vm_reset(&v,1);v.caps[1]=BR_CAP_SERVICE;code[0].imm=0;code[1].imm=8;code[2].imm=BR_SVC_COUNT;ok=ok&&br_vm_load_code(&v,code,4)==0&&br_vm_run(&v,16)==BR_EUNSUPPORTED;br_vm_reset(&v,1);v.caps[1]=BR_CAP_SERVICE;code[2].imm=10;v.hb_=0;ok=ok&&br_vm_load_code(&v,code,4)==0&&br_vm_run(&v,16)==BR_ERESOURCE&&v.trap==BR_TRAP_RESOURCE;br_vm_destroy(&v);return ok;}
static int device_isolation(void){br_memory_ctx a,b;br_vm va,vb;br_device da={11,BR_CAP_SERVICE},db={22,BR_CAP_SERVICE};br_insn c[]={{BR_MOVI,BR_WRAP,0,0,0,0,0,0},{BR_SVC,BR_WRAP,1,0,0,1,0,14},{BR_HALT,BR_WRAP,0,0,0,0,0,0}};int ok;br_memory_adapter_init(&a,BR_ADAPTER_SMARTCARD,1);br_memory_adapter_init(&b,BR_ADAPTER_SMARTCARD,1);if(!init(&va,&br_hal_smartcard,&a,8,&da,1)||!init(&vb,&br_hal_smartcard,&b,8,&db,1))return 0;va.caps[1]=vb.caps[1]=BR_CAP_SERVICE;ok=!br_vm_load_code(&va,c,3)&&!br_vm_load_code(&vb,c,3)&&!br_vm_run(&va,8)&&a.dc_s==1&&b.dc_s==0&&!br_vm_run(&vb,8)&&b.dc_s==1;br_vm_destroy(&va);br_vm_destroy(&vb);return ok;}
static int apdu_negative(void){br_memory_ctx c;br_vm v;uint8_t q[32]={1,BR_APDU_INPUT},r[32];size_t n;int ok;br_memory_adapter_init(&c,BR_ADAPTER_SMARTCARD,1);if(!init(&v,&br_hal_smartcard,&c,8,NULL,0))return 0;q[10]=5;q[11]=0;n=br_apdu(&v,q,12,r,sizeof(r));ok=n==8&&r[0]==0x67&&r[1]==0x00;q[0]=9;n=br_apdu(&v,q,12,r,sizeof(r));ok=ok&&n==8&&r[0]==0x6a&&r[1]==0x80;br_vm_destroy(&v);return ok;}
static int wide_stack(void){br_memory_ctx c;br_vm v;br_insn code[]={{BR_PUSH,BR_WRAP,0,0,0,0,0,0},{BR_POP,BR_WRAP,1,0,0,0,0,0},{BR_HALT,BR_WRAP,0,0,0,0,0,0}};int ok;br_memory_adapter_init(&c,BR_ADAPTER_MEMORY,1);if(!init(&v,&br_hal_memory,&c,8,NULL,0))return 0;br_vm_reg(&v,0)[0]=1;br_vm_reg(&v,0)[BR_LIMBS/2]=2;br_vm_reg(&v,0)[BR_LIMBS-1]=3;ok=!br_vm_load_code(&v,code,3)&&!br_vm_run(&v,8)&&!memcmp(br_vm_reg(&v,0),br_vm_reg(&v,1),BR_LIMBS*8u);br_vm_destroy(&v);return ok;}
static int budget_cancel(void){br_memory_ctx c;br_vm v;br_insn loop={BR_JMP,BR_WRAP,0,0,0,0,0,0};int ok;br_memory_adapter_init(&c,BR_ADAPTER_MEMORY,1);if(!init(&v,&br_hal_memory,&c,8,NULL,0))return 0;ok=!br_vm_load_code(&v,&loop,1)&&br_vm_run(&v,3)==BR_ERESOURCE&&v.trap==BR_TRAP_BUDGET;br_vm_reset(&v,1);v.cn_=1;ok=ok&&!br_vm_load_code(&v,&loop,1)&&br_vm_run(&v,3)==BR_ESTATE&&v.trap==BR_TRAP_CANCEL;br_vm_destroy(&v);return ok;}
static int pointer_validation(void){size_t n=0;br_vm v;return br_vm_create(NULL,NULL,NULL)==BR_EINVAL&&br_image_encode(NULL,0,&n,boot,6,1,0,NULL,0,0)==BR_EINVAL&&br_vm_init(&v)==0&&br_image_load(&v,NULL,0,NULL,0,0)==BR_EIMAGE&&(br_vm_destroy(&v),1);}
int main(void){T("core_selftest",br_core_selftest()==0);T("lc__create_initialize_configure_reset_load_verify_start_step_run_suspend_resume_stop_fault_destroy",lc_());T("explicit_instance_isolation",isolation());T("hal_memory_all_16_calls",memory_hal_contract(&br_hal_memory,BR_ADAPTER_MEMORY));T("hal_deterministic_adapter",memory_hal_contract(&br_hal_deterministic,BR_ADAPTER_DETERMINISTIC));T("hal_bare_metal_adapter",memory_hal_contract(&br_hal_baremetal,BR_ADAPTER_BARE_METAL));T("hal_smart_card_adapter",memory_hal_contract(&br_hal_smartcard,BR_ADAPTER_SMARTCARD));T("posix_adapter_storage_monotonic",file_adapter_contract(0));T("windows_adapter_portable_contract",file_adapter_contract(1));T("same_brim_three_adapters",parity());T("persistence_dual_slot_monotonic_replay",persistence());T("loader_error_model_abi_isa_integrity_replay",error_images());T("sandbox_caps_fixed_host_table_bounds_quotas",sandbox());T("per_instance_device_table",device_isolation());T("apdu_length_pointer_protocol_rejection",apdu_negative());T("wide_1048576_bit_stack_roundtrip",wide_stack());T("execution_budget_and_cancel",budget_cancel());T("public_pointer_validation",pointer_validation());printf("{\"suite\":\"BR-410\",\"tests\":%d,\"failures\":%d,\"result\":\"%s\"}\n",tests,failures,failures?"FAIL":"PASS");return failures?1:0;}
