#include "brvm.h"
#include <stdio.h>
#include <string.h>
static int F,T;
#define X(n,e) do{int q=(e);T++;printf("%s %s\n",q?"PASS":"FAIL",n);if(!q)F++;}while(0)
static int init(br_vm*v){br_vm_config q={4096,64,64,BR_CAP_ALL,NULL,0};return !br_vm_create(v,NULL,NULL)&&!br_vm_initialize(v)&&!br_vm_configure(v,&q);}
static int run(br_vm*v,br_insn*z,size_t n,uint32_t b){return !br_vm_load_code(v,z,n)&&!br_vm_run(v,b);}
static int idle(void){br_vm v;size_t a;int q=init(&v);a=br_vm_allocated_bytes(&v);q=q&&a==BR_UPDATE_BYTES&&a<1024u*1024u;for(unsigned i=0;i<BR_REGS;i++)q=q&&br_vm_word_kind(&v,i)==0&&br_vm_word_bytes(&v,i)==0;br_vm_destroy(&v);return q;}
static int small_const(void){br_vm v;br_insn z[]={{BR_MOVI,0,0,0,0,0,0,42},{BR_MOVI,0,1,0,0,0,0,42},{BR_MOVI,0,2,0,0,0,0,0},{BR_MOVI,0,3,0,0,0,0,1},{BR_HALT,0,0,0,0,0,0,0}};int q=init(&v);size_t a=br_vm_allocated_bytes(&v);q=q&&run(&v,z,5,8)&&br_vm_word_kind(&v,0)==1&&br_vm_word_bytes(&v,0)==8&&br_vm_word_kind(&v,2)==0&&v.cpn_==1&&br_vm_allocated_bytes(&v)==a;br_vm_destroy(&v);return q;}
static int sparse_max(void){br_vm v;br_insn z[]={{BR_MOVI,0,0,0,0,0,0,1},{BR_SHL,BR_WRAP,1,0,0,0,0,BR_WORD_BITS-1u},{BR_BITTST,0,0,1,0,0,0,BR_WORD_BITS-1u},{BR_HALT,0,0,0,0,0,0,0}};int q=init(&v);q=q&&run(&v,z,4,8)&&br_vm_word_kind(&v,1)==2&&br_vm_word_bytes(&v,1)==8&&!(v.flags&BR_FLAG_ZERO)&&br_vm_allocated_bytes(&v)==BR_UPDATE_BYTES;br_vm_destroy(&v);return q;}
static int cow(void){br_vm v;br_insn z[]={{BR_NOT,0,0,0,0,0,0,0},{BR_MOV,0,1,0,0,0,0,0},{BR_SHR,0,1,1,0,0,0,1},{BR_HALT,0,0,0,0,0,0,0}};void*p;size_t a;int q=init(&v);q=q&&!br_vm_load_code(&v,z,4)&&!br_vm_start(&v)&&!br_vm_step(&v);p=v.regs[0].p;a=br_vm_allocated_bytes(&v);q=q&&p&&br_vm_word_kind(&v,0)==3&&!br_vm_step(&v)&&v.regs[1].p==p&&br_vm_allocated_bytes(&v)==a&&!br_vm_step(&v)&&v.regs[1].p!=p&&v.regs[0].p==p;br_vm_destroy(&v);return q;}
static int normalize(void){br_vm v;br_insn z[]={{BR_NOT,0,0,0,0,0,0,0},{BR_MOVI,0,1,0,0,0,0,1},{BR_AND,0,2,0,1,0,0,0},{BR_HALT,0,0,0,0,0,0,0}};int q=init(&v);q=q&&run(&v,z,4,8)&&br_vm_word_kind(&v,0)==3&&br_vm_word_kind(&v,2)==1&&br_vm_word_bytes(&v,2)==8;br_vm_destroy(&v);return q;}
static int stack_reclaim(void){br_vm v;br_insn z[]={{BR_MOVI,0,0,0,0,0,0,7},{BR_PUSH,0,0,0,0,0,0,0},{BR_POP,0,1,0,0,0,0,0},{BR_HALT,0,0,0,0,0,0,0}};int q=init(&v);q=q&&!br_vm_load_code(&v,z,4)&&!br_vm_start(&v)&&!br_vm_step(&v)&&!br_vm_step(&v)&&br_vm_stack_bytes(&v)==8&&!br_vm_step(&v)&&br_vm_stack_bytes(&v)==0&&v.sp==0;br_vm_destroy(&v);return q;}
static int stack_quota(void){br_vm v;br_insn z[]={{BR_MOVI,0,0,0,0,0,0,7},{BR_PUSH,0,0,0,0,0,0,0},{BR_PUSH,0,0,0,0,0,0,0}};int q=init(&v);q=q&&!br_vm_set_limits(&v,BR_VM_HEAP_BYTES,8,BR_SCRATCH_BYTES)&&!br_vm_load_code(&v,z,3)&&br_vm_run(&v,8)==BR_ERESOURCE&&v.trap==BR_TRAP_STACK_OVERFLOW;br_vm_destroy(&v);return q;}
static int depth_quota(void){br_vm v;br_insn z[]={{BR_PUSH,0,0,0,0,0,0,0},{BR_JMP,0,0,0,0,0,0,0}};int q=init(&v);q=q&&!br_vm_load_code(&v,z,2)&&br_vm_run(&v,600)==BR_ERESOURCE&&v.trap==BR_TRAP_STACK_OVERFLOW&&v.sp==BR_STACK_WORDS;br_vm_destroy(&v);return q;}
static int scratch_quota(void){br_vm v;br_insn z[]={{BR_NOT,0,0,0,0,0,0,0}};int q=init(&v);q=q&&!br_vm_set_limits(&v,BR_VM_HEAP_BYTES,BR_STACK_BYTES,64)&&!br_vm_load_code(&v,z,1)&&br_vm_run(&v,2)==BR_ERESOURCE&&v.trap==BR_TRAP_SCRATCH;br_vm_destroy(&v);return q;}
static int oom(void){br_vm v;br_insn z[]={{BR_NOT,0,0,0,0,0,0,0}};int q=init(&v);q=q&&!br_vm_set_limits(&v,BR_UPDATE_BYTES+BR_WORD_BYTES,BR_STACK_BYTES,BR_WORD_BYTES)&&!br_vm_load_code(&v,z,1)&&br_vm_run(&v,2)==BR_ERESOURCE&&v.trap==BR_TRAP_OOM;br_vm_destroy(&v);return q;}
static int width_trap(void){br_vm v;br_insn z[]={{BR_BITTST,0,0,0,0,0,0,BR_WORD_BITS}};int q=init(&v);q=q&&!br_vm_load_code(&v,z,1)&&br_vm_run(&v,2)==BR_EBOUNDS&&v.trap==BR_TRAP_WORD_WIDTH;br_vm_destroy(&v);return q;}
static int wide_result(void){br_vm v;br_insn z[]={{BR_MOVI,0,0,0,0,0,0,1},{BR_SHL,0,1,0,0,0,0,BR_WORD_BITS-1u},{BR_ADD,0,2,1,0,0,0,0},{BR_HALT,0,0,0,0,0,0,0}};const uint64_t*p;int q=init(&v);q=q&&run(&v,z,4,8);p=br_vm_reg_const(&v,2);q=q&&p&&p[0]==1&&p[BR_LIMBS-1]==(UINT64_C(1)<<63);br_vm_destroy(&v);return q;}
static int deterministic(void){br_vm a,b;br_insn z[]={{BR_MOVI,0,0,0,0,0,0,1},{BR_SHL,0,1,0,0,0,0,70000},{BR_ADD,0,2,1,0,0,0,0},{BR_SHR,0,3,2,0,0,0,13},{BR_HALT,0,0,0,0,0,0,0}};int q=init(&a)&&init(&b);q=q&&run(&a,z,5,16)&&run(&b,z,5,16)&&a.ip==b.ip&&a.status==b.status&&a.trap==b.trap&&a.flags==b.flags&&br_vm_word_kind(&a,3)==br_vm_word_kind(&b,3)&&br_vm_word_bytes(&a,3)==br_vm_word_bytes(&b,3)&&br_vm_allocated_bytes(&a)==br_vm_allocated_bytes(&b);br_vm_destroy(&a);br_vm_destroy(&b);return q;}
int main(void){X("idle_no_36mb_preallocation",idle());X("small_constant_pool_no_heap_word",small_const());X("sparse_maximum_high_bit",sparse_max());X("copy_on_write_dense_word",cow());X("normalize_dense_to_small",normalize());X("stack_allocate_and_reclaim",stack_reclaim());X("stack_byte_quota_trap",stack_quota());X("stack_depth_quota_trap",depth_quota());X("scratch_quota_trap",scratch_quota());X("per_vm_oom_trap",oom());X("word_width_trap",width_trap());X("maximum_1048576_bit_result",wide_result());X("deterministic_semantics_and_allocation",deterministic());printf("{\"suite\":\"BR-460\",\"tests\":%d,\"failures\":%d,\"result\":\"%s\"}\n",T,F,F?"FAIL":"PASS");return F?1:0;}
