#define _POSIX_C_SOURCE 200809L
#include "brvm.h"
#include "brtrust.h"
#include "br_adapters.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
typedef struct{uint8_t*p;size_t n;}B;static int F,N;
#define T(n,e) do{int ok_=(e);N++;printf("%s %s\n",ok_?"PASS":"FAIL",n);if(!ok_)F++;}while(0)
static B rd(const char*n){char p[256];FILE*f;long z;B b={0};snprintf(p,sizeof p,"tests/trust_fixtures/%s",n);f=fopen(p,"rb");if(!f)return b;fseek(f,0,2);z=ftell(f);fseek(f,0,0);b.p=malloc((size_t)z);b.n=fread(b.p,1,(size_t)z,f);fclose(f);return b;}static void cl(const char*p){char q[256];unsigned i;for(i=0;i<2;i++){snprintf(q,sizeof q,"%s.ctl.%u",p,i);remove(q);snprintf(q,sizeof q,"%s.ctl.%u.tmp",p,i);remove(q);snprintf(q,sizeof q,"%s.img.%u",p,i);remove(q);snprintf(q,sizeof q,"%s.img.%u.tmp",p,i);remove(q);}for(i=0;i<6;i++){snprintf(q,sizeof q,"%s.obj.%u",p,i);remove(q);snprintf(q,sizeof q,"%s.obj.%u.tmp",p,i);remove(q);}snprintf(q,sizeof q,"%s.mono",p);remove(q);snprintf(q,sizeof q,"%s.mono.tmp",p);remove(q);snprintf(q,sizeof q,"%s.lock",p);remove(q);}static int nv(br_vm*v,br_posix_ctx*c,br_trust*t,const char*p){br_vm_config q={4096,64,64,BR_CAP_ALL,0,0};return br_posix_adapter_init(c,p)||br_vm_create(v,&br_hal_posix,c)||br_vm_initialize(v)||br_vm_configure(v,&q)||br_trust_init(t,v,0,0);}static uint32_t g32(const uint8_t*p){return p[0]|(uint32_t)p[1]<<8|(uint32_t)p[2]<<16|(uint32_t)p[3]<<24;}static uint32_t crc(const uint8_t*d,size_t n){uint32_t c=~0u;size_t i;unsigned b;for(i=0;i<n;i++){c^=d[i];for(b=0;b<8;b++)c=(c>>1)^(0xedb88320u&(0u-(c&1u)));}return~c;}
static int (*OSW)(void*,uint32_t,const uint8_t*,size_t),(*OSC)(void*,uint32_t),(*OMC)(void*,uint64_t);static int FP,FC;static int fsw(void*x,uint32_t i,const uint8_t*d,size_t n){if(++FC==FP)return BR_EIO;return OSW(x,i,d,n);}static int fsc(void*x,uint32_t i){if(++FC==FP)return BR_EIO;return OSC(x,i);}static int fmc(void*x,uint64_t v){if(++FC==FP)return BR_EIO;return OMC(x,v);}static br_hal FH;
static int setup1(const char*p,B p1,B i1,B m1,br_vm*v,br_posix_ctx*c,br_trust*t){cl(p);if(nv(v,c,t,p)||br_trust_apply_policy(t,p1.p,p1.n)||br_trust_install(t,i1.p,i1.n,m1.p,m1.n))return-1;return 0;}
static int proclock(const char*p){br_posix_ctx a,b;pid_t k;int st=1;if(br_posix_adapter_init(&a,p)||br_hal_posix.lock(&a))return 0;k=fork();if(k==0){int r=br_posix_adapter_init(&b,p)||br_hal_posix.lock(&b)==0;_exit(r?1:0);}if(k>0)waitpid(k,&st,0);br_hal_posix.unlock(&a);return k>0&&WIFEXITED(st)&&WEXITSTATUS(st)==0;}
static int recoverg(const char*p,B pol,uint32_t g){br_vm v={0};br_posix_ctx c;br_trust t;int r=nv(&v,&c,&t,p);if(!r)r=br_trust_apply_policy(&t,pol.p,pol.n);if(!r)r=br_trust_recover(&t);r=!r&&v.pg_==g&&v.sa_;br_vm_destroy(&v);return r;}
static int faultcase(int k,const char*p,B p1,B p2,B i1,B i2,B m1,B m2){br_vm v={0};br_posix_ctx c;br_trust t;int r,ok;if(setup1(p,p1,i1,m1,&v,&c,&t))return 0;if(br_trust_apply_policy(&t,p2.p,p2.n)){br_vm_destroy(&v);return 0;}FH=br_hal_posix;OSW=FH.sw_;OSC=FH.sc_;OMC=FH.mc_;FH.sw_=fsw;FH.sc_=fsc;FH.mc_=fmc;FP=k;FC=0;v.hal=&FH;r=br_trust_install(&t,i2.p,i2.n,m2.p,m2.n);br_vm_destroy(&v);ok=r!=0&&recoverg(p,k<7?p1:p2,k<7?1:2);cl(p);return ok;}
static int objsvc(br_vm*v,int w,unsigned id,uint32_t ns,const uint8_t*in,size_t n,uint8_t*out,size_t*on){br_insn c[2]={{BR_SVC,BR_WRAP,2,0,1,0,(uint16_t)id,w?BR_SVC_STORAGE_WRITE:BR_SVC_STORAGE_READ},{BR_HALT,BR_WRAP,0,0,0,0,0,0}};int r;br_vm_reset(v,1);v->cw_=ns;if(w&&n)memcpy(v->memory+128,in,n);br_vm_reg(v,0)[0]=128;br_vm_reg(v,1)[0]=n;if((r=br_vm_load_code(v,c,2)))return r;v->caps[0]=BR_CAP_ALL;r=br_vm_run(v,8);if(!r&&!w&&out&&on){*on=(size_t)br_vm_reg(v,2)[0];memcpy(out,v->memory+128,*on);}return r;}
int main(void){const char*p=".build/t450p";B p1=rd("policy_v1.brtp"),p2=rd("policy_rotated.brtp"),i1=rd("image_r1.brimg"),i2=rd("image_r2.brimg"),m1=rd("manifest_r1.brmf"),m2=rd("manifest_r2.brmf");br_vm v={0};br_posix_ctx c,c2;br_trust t;int r;uint8_t b[512];size_t z=0;char q[256];struct stat st;
cl(p);r=nv(&v,&c,&t,p);if(!r)r=br_trust_apply_policy(&t,p1.p,p1.n);if(!r)r=br_trust_install(&t,i1.p,i1.n,m1.p,m1.n);T("install_generation1",!r&&v.pg_==1&&v.as_==1);br_vm_destroy(&v);T("recover_generation1",recoverg(p,p1,1));r=nv(&v,&c,&t,p);if(!r)r=br_trust_apply_policy(&t,p1.p,p1.n);if(!r)r=br_trust_recover(&t);if(!r)r=br_trust_apply_policy(&t,p2.p,p2.n);if(!r)r=br_trust_install(&t,i2.p,i2.n,m2.p,m2.n);T("install_generation2",!r&&v.pg_==2&&v.as_==0);br_vm_destroy(&v);T("latest_authenticated_committed_wins",recoverg(p,p2,2));
snprintf(q,sizeof q,"%s.ctl.0",p);{FILE*f=fopen(q,"rb");z=f?fread(b,1,sizeof b,f):0;if(f)fclose(f);}T("control_record_v2_signed_binding",z==512&&!memcmp(b,"BRC2",4)&&b[4]==2&&b[5]==1&&b[6]==0&&g32(b+8)==2&&!memcmp(b+64,m2.p,m2.n)&&g32(b+508)==crc(b,508));
for(r=1;r<=7;r++){char n[64];snprintf(n,sizeof n,"power_loss_mutation_stage_%d",r);T(n,faultcase(r,p,p1,p2,i1,i2,m1,m2));}
T("interruption_before_update_keeps_previous_good",setup1(p,p1,i1,m1,&v,&c,&t)==0&&(br_vm_destroy(&v),recoverg(p,p1,1)));r=setup1(p,p1,i1,m1,&v,&c,&t);if(!r)r=br_trust_apply_policy(&t,p2.p,p2.n);if(!r)r=br_trust_install(&t,i2.p,i2.n,m2.p,m2.n);br_vm_destroy(&v);T("interruption_after_activation_recovers_new",!r&&recoverg(p,p2,2));r=nv(&v,&c,&t,p);if(!r)r=br_trust_apply_policy(&t,p2.p,p2.n);if(!r)r=br_trust_recover(&t);if(!r)r=br_vm_run(&v,64);br_vm_destroy(&v);T("after_first_successful_boot_recovers_new",!r&&recoverg(p,p2,2));
cl(p);r=setup1(p,p1,i1,m1,&v,&c,&t);snprintf(q,sizeof q,"%s.ctl.1",p);if(!r){FILE*f=fopen(q,"r+b");if(f){fseek(f,30,0);fputc(0xff,f);fclose(f);}}br_vm_destroy(&v);T("corrupted_control_rejected",!recoverg(p,p1,1));
cl(p);r=setup1(p,p1,i1,m1,&v,&c,&t);snprintf(q,sizeof q,"%s.img.1",p);if(!r){FILE*f=fopen(q,"r+b");if(f){fseek(f,90,0);fputc(0xaa,f);fclose(f);}}br_vm_destroy(&v);T("image_control_digest_mismatch_rejected",!recoverg(p,p1,1));
cl(p);r=setup1(p,p1,i1,m1,&v,&c,&t);snprintf(q,sizeof q,"%s.ctl.1",p);if(!r){FILE*f=fopen(q,"r+b");if(f){if(fread(b,1,512,f)!=512){fclose(f);f=NULL;}}if(f){b[5]=0;b[508]=b[509]=b[510]=b[511]=0;{uint32_t cc=crc(b,508);b[508]=cc;b[509]=cc>>8;b[510]=cc>>16;b[511]=cc>>24;}rewind(f);fwrite(b,1,512,f);fclose(f);}}br_vm_destroy(&v);T("pending_control_never_bootable",!recoverg(p,p1,1));
cl(p);r=setup1(p,p1,i1,m1,&v,&c,&t);snprintf(q,sizeof q,"%s.ctl.1",p);if(!r&&truncate(q,20)!=0)r=-1;br_vm_destroy(&v);T("truncated_control_rejected",!r&&!recoverg(p,p1,1));
cl(p);T("path_traversal_rejected",br_posix_adapter_init(&c,"/tmp/../brbad")!=0);br_posix_adapter_init(&c,p);br_posix_adapter_init(&c2,p);T("multiple_host_process_lock_exclusion",proclock(p));memset(b,7,3);r=br_hal_posix.sw_(&c,BR_STORAGE_OBJECT0,b,3)||br_hal_posix.sc_(&c,BR_STORAGE_OBJECT0);snprintf(q,sizeof q,"%s.obj.0",p);T("restrictive_file_permissions",!r&&!stat(q,&st)&&(st.st_mode&077)==0);T("storage_erase_status",br_hal_posix.se_(&c,BR_STORAGE_OBJECT0)==0&&br_hal_posix.sr_(&c,BR_STORAGE_OBJECT0,b,sizeof b,&z)!=0);remove(q);snprintf(q,sizeof q,"%s.obj.0.tmp",p);T("symlink_temp_rejected",symlink("/etc/passwd",q)==0&&br_hal_posix.sw_(&c,BR_STORAGE_OBJECT0,b,3)!=0);remove(q);
{br_memory_ctx mc;br_vm x={0};br_vm_config cfg={64,16,16,BR_CAP_ALL,0,0};uint8_t o[500],d[500];size_t dn=0;memset(d,0x5a,100);br_memory_adapter_init(&mc,BR_ADAPTER_MEMORY,1);r=br_vm_create(&x,&br_hal_memory,&mc)||br_vm_initialize(&x)||br_vm_configure(&x,&cfg);T("guest_object_write_versioned",!r&&!objsvc(&x,1,0,7,d,100,0,0)&&mc.length[4]==512&&!memcmp(mc.object[0],"BRO1",4)&&mc.object[0][4]==1);T("guest_object_read_namespace_integrity",!objsvc(&x,0,0,7,0,100,o,&dn)&&dn==100&&!memcmp(o,d,100));T("guest_object_namespace_isolation",objsvc(&x,0,0,8,0,100,o,&dn)==BR_EINTEGRITY);mc.object[0][20]^=1;T("guest_object_tamper_rejected",objsvc(&x,0,0,7,0,100,o,&dn)==BR_EINTEGRITY);T("guest_object_quota_enforced",objsvc(&x,1,0,7,d,465,0,0)==BR_EBOUNDS);memcpy(mc.object[1],"old",3);mc.length[5]=3;T("legacy_guest_object_migrates_to_v1",!objsvc(&x,0,1,0,0,16,o,&dn)&&dn==3&&!memcmp(o,"old",3)&&mc.length[5]==512&&!memcmp(mc.object[1],"BRO1",4));br_vm_reset(&x,1);T("checkpoint_state_isolated_from_secure_control",br_vm_save(&x)==0&&mc.length[0]==0&&mc.length[1]==0&&(mc.length[8]==512||mc.length[9]==512));br_vm_destroy(&x);}
cl(p);free(p1.p);free(p2.p);free(i1.p);free(i2.p);free(m1.p);free(m2.p);printf("{\"suite\":\"BR-450\",\"tests\":%d,\"failures\":%d,\"result\":\"%s\"}\n",N,F,F?"FAIL":"PASS");return F?1:0;}
